server:
  port: 8100
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://175.24.9.43:3306/wuliu
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: pxswzt
    type: com.alibaba.druid.pool.DruidDataSource
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka